
import SulfurAI
print("-------------------")
print("")
print(SulfurAI.render_dataprofile())
#print(SulfurAI.render_dataprofile(USE_API=True,API_KEY="",API_MODEL="gemini-2.5-flash"))
print(SulfurAI.return_annotations_dataprofiles())
print(SulfurAI.return_offline_dataprofiles())
print("-------------------")
print("")

print("-------------------")
print("")
print("DATA_PROFILES_RETURN")
print(SulfurAI.return_dataprofiles())
print("-------------------")
print("")
print("DATA_PROFILES_RETURN_TYPE")
print(type(SulfurAI.return_dataprofiles()))
print("-------------------")
print("")
print("DATA_PROFILES_RETURN_ADVS")
profiles = SulfurAI.return_dataprofiles()
print(profiles)
print(profiles["data"]["ADVANCED_SUMMARY"])
print("-------------------")
print("")
print(profiles["data"]["NORMAL_SUMMARY"])
